version: 2.1

workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              python_image:
                - "python:3.5-slim"
                - "python:3.6-slim"
                - "python:3.7-slim"
                - "python:3.8-slim"
                - "python:3.9-slim"
                - "pypy:3-slim-buster"
              django_version:
                - "master"
                - "3.0.x" # 3.0 supports python 3.6 to 3.9
                - "2.2.x" # 2.2 supports python 3.5 to 3.9
            exclude:
              - python_image: "python:3.5-slim"
                django_version: "master"
              - python_image: "python:3.5-slim"
                django_version: "3.0.x"
jobs:
  test:
    parameters:
      python_image:
        type: string
      django_version:
        type: string
    docker:
      - image: << parameters.python_image >>
        # auth:
        #   username: $DOCKER_USER
        #   password: $DOCKER_PASS
        environment:
          DJANGO_VERSION: << parameters.django_version >>
          PYTHON_IMAGE: << parameters.python_image >>
    steps:
      - checkout
      - run:
          name: install
          command: pip install tox coveralls
      - when:
          condition:
            not:
              or:
                - equal: [ "pypy:3-slim-buster", << parameters.python_image >> ]
          steps:
            - run:
                name: test cpython
                command: |
                  PYTHON_VERSION="$(python --version 2>&1 | cut -d ' ' -f 2 | cut -d '.' -f 1,2)"
                  echo "$PYTHON_VERSION-$DJANGO_VERSION"
                  tox -e "$PYTHON_VERSION-$DJANGO_VERSION"
      - when:
          condition:
            or:
              - equal: [ "pypy:3-slim-buster", << parameters.python_image >> ]
          steps:
            - run:
                name: test pypy
                command: |
                  PYTHON_VERSION="pypy$(pypy --version 2>&1 | head -n 1 | cut -d ' ' -f 2 | cut -d '.' -f 1)"
                  echo "$PYTHON_VERSION-$DJANGO_VERSION"
                  tox -e "$PYTHON_VERSION-$DJANGO_VERSION"
      - run:
          name: report coverage
          command: coveralls
